export const season2VenueNames = [
  "[Legacy] Kentucky Speedway",
  "[Legacy] Michigan International Speedway",
  "[Legacy] Phoenix Raceway",
  "[Legacy] Pocono Raceway",
  "[Legacy] Texas Motor Speedway",
  "Adelaide Street Circuit",
  "Algarve International Circuit",
  "Auto Club Speedway",
  "Autodromo Internazionale del Mugello",
  "Autodromo Internazionale Enzo e Dino Ferrari",
  "Autodromo Nazionale Monza",
  "Autódromo Hermanos Rodríguez",
  "Autódromo José Carlos Pace",
  "Barber Motorsports Park",
  "Bark River International Raceway",
  "Brands Hatch Circuit",
  "Bristol Motor Speedway",
  "Canadian Tire Motorsports Park",
  "Cedar Lake Speedway",
  "Charlotte Motor Speedway",
  "Chicago Street Course",
  "Chicagoland Speedway",
  "Chili Bowl",
  "Circuit de Barcelona Catalunya",
  "Circuit de Lédenon",
  "Circuit de Nevers Magny-Cours",
  "Circuit de Spa-Francorchamps",
  "Circuit des 24 Heures du Mans",
  "Circuit Gilles Villeneuve",
  "Circuit of the Americas",
  "Circuit Zandvoort",
  "Circuit Zolder",
  "Circuito de Jerez - Ángel Nieto",
  "Circuito de Navarra",
  "Concord Speedway",
  "Crandon International Raceway",
  "Darlington Raceway",
  "Daytona International Speedway",
  "Daytona International Speedway - Oval",
  "Daytona Rallycross and Dirt Road",
  "Detroit Grand Prix at Belle Isle",
  "Donington Park Racing Circuit",
  "Dover Motor Speedway",
  "EchoPark Speedway (Atlanta)",
  "Eldora Speedway",
  "Fairbury Speedway",
  "Federated Auto Parts Raceway at I-55",
  "Firebird Motorsports Park",
  "Five Flags Speedway",
  "Fuji International Speedway",
  "Hickory Motor Speedway",
  "Hockenheimring Baden-Württemberg",
  "Homestead Miami Speedway",
  "Hungaroring",
  "Huset's Speedway",
  "Indianapolis Motor Speedway",
  "Iowa Speedway",
  "Iowa Speedway - Oval",
  "Iowa Speedway - Rallycross",
  "iRacing Superspeedway",
  "Irwindale Speedway - Outer",
  "Kansas Speedway",
  "Kentucky Speedway",
  "Kevin Harvick's Kern Raceway",
  "Knockhill Racing Circuit",
  "Knoxville Raceway",
  "Kokomo Speedway - Tires in",
  "Kokomo Speedway - Tires out",
  "LA Coliseum Raceway",
  "Langley Speedway",
  "Lanier National Speedway",
  "Lanier National Speedway - Asphalt",
  "Las Vegas Motor Speedway",
  "Lernerville Speedway",
  "Limaland Motorsports Park",
  "Lime Rock Park",
  "Lime Rock Park - Classic",
  "Lime Rock Park - West Bend Chicane",
  "Lincoln Speedway",
  "Long Beach Street Circuit",
  "Lucas Oil Indianapolis Raceway Park",
  "Lucas Oil Speedway",
  "Lucas Oil Speedway - Dirt Oval",
  "Lånkebanen (Hell RX)",
  "Martinsville Speedway",
  "Miami International Autodrome",
  "Michigan International Speedway",
  "Mid-Ohio Sports Car Course",
  "Millbridge Speedway",
  "Misano World Circuit Marco Simoncelli",
  "Mobility Resort Motegi",
  "MotorLand Aragón",
  "Motorsport Arena Oschersleben",
  "Mount Panorama Circuit",
  "Myrtle Beach Speedway",
  "Nashville Fairgrounds Speedway",
  "Nashville Fairgrounds Speedway - Mini",
  "Nashville Superspeedway",
  "New Hampshire Motor Speedway",
  "New Smyrna Speedway",
  "North Wilkesboro Speedway",
  "North Wilkesboro Speedway - Oval",
  "Nürburgring Combined",
  "Nürburgring Grand-Prix-Strecke",
  "Nürburgring Nordschleife",
  "Okayama International Circuit",
  "Oran Park Raceway",
  "Oran Park Raceway - South",
  "Oswego Speedway",
  "Oulton Park Circuit",
  "Oxford Plains Speedway",
  "Phillip Island Circuit",
  "Phoenix Raceway",
  "Phoenix Raceway - Oval w/open dogleg",
  "Pocono Raceway",
  "Port Royal Speedway",
  "Portland International Raceway",
  "Red Bull Ring",
  "Richmond Raceway",
  "Road America",
  "Road Atlanta",
  "Rockingham Speedway",
  "Rudskogen Motorsenter",
  "Sachsenring",
  "Sandown International Motor Raceway",
  "Sebring International Raceway",
  "Shell V-Power Motorsport Park at The Bend",
  "Silverstone Circuit",
  "Slinger Speedway",
  "Snetterton Circuit",
  "Sonoma Raceway",
  "South Boston Speedway",
  "Southern National Motorsports Park",
  "St. Petersburg Grand Prix",
  "Stafford Motor Speedway",
  "Summit Point Raceway",
  "Suzuka International Racing Course",
  "Talladega Superspeedway",
  "Texas Motor Speedway",
  "The Bullring",
  "The Dirt Track at Charlotte",
  "The Milwaukee Mile",
  "Thompson Speedway Motorsports Park",
  "Thruxton Circuit",
  "Tsukuba Circuit - 2000 Full",
  "USA International Speedway",
  "USA International Speedway - Asphalt",
  "Virginia International Raceway",
  "Virginia International Raceway - Grand Course",
  "Virginia International Raceway - North Course",
  "Volusia Speedway Park",
  "Watkins Glen International - Boot",
  "Watkins Glen International - Classic Boot",
  "Watkins Glen International - Cup",
  "WeatherTech Raceway at Laguna Seca",
  "Weedsport Speedway",
  "Wild West Motorsports Park",
  "Williams Grove Speedway",
  "Willow Springs International Raceway - Big Willow",
  "Winton Motor Raceway",
  "Winton Motor Raceway - Club Circuit",
  "Winton Motor Raceway - National Circuit",
  "World Wide Technology Raceway (Gateway)"
] as const
